#!/usr/bin/python3
import subprocess
import sys
import os
def get_current_user():
    try:
        script_dir = os.path.dirname(os.path.abspath(__file__))
        user_file_path = os.path.join(script_dir, "../data/check_user_file.txt")
        with open(user_file_path, "r") as user_file:
            current_user = user_file.read().strip()
            return current_user
    except FileNotFoundError as e:
        print(f"Error reading user file: {e}")
        return None
def install_package(package_name):
    
      owner =get_current_user()
      if owner != 'root':
                print("Error: You need root permissions to install package.")
      try:
        subprocess.run(['sudo', 'apt', 'install', '-y', package_name], check=True)
        print(f"Package '{package_name}' installed successfully.")
      except subprocess.CalledProcessError as e:
        print(f"Error installing package '{package_name}': {e.stderr}")
        sys.exit(1)

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: python script.py <package_name>")
        sys.exit(1)

    package_name = sys.argv[1]

    # Install the specified package
    install_package(package_name)
